@startuml
'https://plantuml.com/class-diagram

class Solution42{
	+main()
	'NameSort ns = new NameSorter()
	'emp.readNames("input.txt")
	'emp.displayEmployees()
}


class Employee {
	-ArrayList<Strings> information; //instance variable every method has accsess to this
	+readNames(String fileName): information
	+displayEmployees(): information
}

Solution42 -- Employee

@enduml