@startuml
'https://plantuml.com/class-diagram

class Solution41{
	+main()
	'NameSort ns = new NameSorter()
	'ns.readNames("input.txt")
	'ns.sortNames()
	'ns.writeNames("output.txt")
}


class nameSorter {
	-ArrayList<Strings> names; //instance variable every method has access to this
	+readNames(String fileName)
	+sortNames()
	+writeNames(String fileName)
}

Solution41 -- nameSorter

@enduml